server:
  port: ${PORT:8081}
  session-timeout: 30
  error:
    path: /error
    whitelabel:
      enabled: true
    include-stacktrace: always
  tomcat:
    access-log-enabled: true
    basedir: D:\\server\\store\\merchant
spring:
  main: 
    web-environment: true
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf: 
    mode: LEGACYHTML5     
  
logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.boot: INFO
  file: merchant_store.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
       
zuul: 
  ignored-services: '*'
  routes:
    api-gateway: /api/**

       
    
      
   
 
     
    
  