server:
  port: ${port:8081}
  session-timeout: 30
  error:
    path: /error
    whitelabel:
      enabled: true
    include-stacktrace: always
  tomcat:
    access-log-enabled: true
    basedir: D:\\esykart\\server\\store\\merchant
spring: 
  main: 
    web-environment: true
  datasource:
    name: MerchantDS
    max-idle: 3
    max-active: 10
    max-wait: 1000
    jmx-enabled: true
    username: postgres
    password: postgres
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    continue-on-error: false
    validation-query: SELECT 1
    min-evictable-idle-time-millis: 30000
    time-between-eviction-runs-millis: 1
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:5432/esykart-merchant
  jpa:
    show-sql: true
    open-in-view: false
    database: POSTGRESQL
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  mvc: 
    throw-exception-if-no-handler-found: true
  thymeleaf: 
    mode: LEGACYHTML5         
  
logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.boot: INFO
  file: D:\\esykart\\logs\\merchant_store.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
      
zuul: 
  ignored-services: '*'
  routes:
    orderService: 
        path: /ordres/**
        stripPrefix: false
        service-id: apigateway
    offerService: 
        path: /offers/**
        stripPrefix: false
        service-id: apigateway
    productService:  
        path: /products/**
        stripPrefix: false
        service-id: apigateway
    customerService: 
        path: /customers/**
        stripPrefix: false
        service-id: apigateway      
    merchantService: 
        path: /merchants/**
        stripPrefix: false
        service-id: apigateway        
             
eureka:  
  client: 
    serviceUrl: 
      defaultZone: http://127.0.0.1:8761/eureka/   