spring:
  main: 
    web-environment: true    
    
logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
  file: D:\\esykart\\logs\\apigateway.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    
ribbon:
  eureka:
   enabled: false

OFFER-SERVICE: 
  ribbon:
    listOfServers: http://127.0.0.1:9003/   
    
ORDER-SERVICE: 
  ribbon:
    listOfServers: http://127.0.0.1:9003/   
    
PRODUCT-SERVICE: 
  ribbon:
    listOfServers: http://127.0.0.1:9003/              

CUSTOMER-SERVICE: 
  ribbon:
    listOfServers: http://127.0.0.1:9002/
    
MERCHANT-SERVICE: 
  ribbon:
    listOfServers: http://127.0.0.1:9003/   