server:
  port: ${port:9000}
  tomcat:
    access-log-enabled: true
    basedir: D:\\esykart\\server\\apigateway
    
spring:
  main: 
    web-environment: true    
    
logging:
  level:
    com.netflix.discovery: INFO
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
  file: D:\\esykart\\server\\apigateway\\logs\\apigateway.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/