server:
  port: ${port:9004}
  display-name: Notification Service
  tomcat:
    access-log-enabled: true
    basedir: D:\\esykart\\server\\notification
    
spring:
  main:
    web-environment: true
  datasource:
    name: NotificationDS
    max-idle: 3
    max-active: 10
    max-wait: 1000
    jmx-enabled: true
    username: postgres
    password: postgres
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    continue-on-error: false
    validation-query: SELECT 1
    min-evictable-idle-time-millis: 30000
    time-between-eviction-runs-millis: 1
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:5432/esykart-notification
  jpa:
    database: POSTGRESQL
  mail:
    protocol: smtp
    host: localhost
    port: 8888
    username: test
    password: test
    test-connection: true
    properties: 
       test: test
          
logging:
  level:
    com.netflix.discovery: INFO
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
  file: D:\\esykart\\logs\\notification_service.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    
      