server:
  port: ${port:9004}
 
spring:
  h2:
    console:
      enabled: true
  jpa: 
    show-sql: true
    open-in-view: false
    database: H2
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  main: 
    web-environment: true
  mail:
    protocol: smtp
    host: localhost
    port: 8888
    username: test
    password: test
    test-connection: true
    properties: 
       test: test
            
      
logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
 
    