server:
  port: ${PORT:9009} 
  display-name: Esykart Shipping
  tomcat:
    access-log-enabled: true
    basedir: D:\\esykart\\server\\store
    
spring:
  main: 
    web-environment: true
  datasource:
    name: StoreDS
    max-idle: 3
    max-active: 10
    max-wait: 1000
    jmx-enabled: true
    username: postgres
    password: postgres
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    continue-on-error: false
    validation-query: SELECT 1
    min-evictable-idle-time-millis: 30000
    time-between-eviction-runs-millis: 1
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:5432/esykart-store
  jpa:
    database: POSTGRESQL
      
logging:
  level:
    com.netflix.discovery: INFO
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
  file: D:\\esykart\\logs\\store_service.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/