server:
  port: ${port:8080}
  display-name: Customer Store
  session-timeout: 30
  error:
    path: /error
  tomcat:
    access-log-enabled: true
    basedir: D:\\esykart\\server\\store\\customer
    
spring:
  main: 
    web-environment: true
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf: 
    mode: LEGACYHTML5     
  
logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.boot: INFO
  file: D:\\esykart\\logs\\customer_store.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
 
zuul: 
  ignored-services: '*'
  routes:
    orderService: 
        path: /ordres/**
        stripPrefix: false
        service-id: apigateway
    offerService: 
        path: /offers/**
        stripPrefix: false
        service-id: apigateway
    productService:  
        path: /products/**
        stripPrefix: false
        service-id: apigateway
    customerService: 
        path: /customers/**
        stripPrefix: false
        service-id: apigateway      
    merchantService: 
        path: /merchants/**
        stripPrefix: false
        service-id: apigateway        
             
ribbon:
  eureka:
    enabled: false

apigateway:
  ribbon:
    listOfServers: http://localhost:9000     
  