spring:
  main: 
    web-environment: true
  datasource:
    jndi-name: java:comp/env/jdbc/OrderDS
  jpa:
    database: POSTGRESQL

logging:
  level:
    com.webientsoft.esykart: DEBUG
    org.springframework.cloud: INFO
  file: D:\\esykart\logs\\order_service.log
  pattern:
    file: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
    